color: null
fieldLayouts:
  eef6f4e8-aaab-43ad-a484-ac5fb10b854f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-13T07:48:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5c296ab4-e5cf-4333-862a-a9d071f75cbd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-13T07:48:42+00:00'
            elementCondition: null
            fieldUid: a536dc09-ff34-40c6-9e0f-ab3cc3f4ce8e # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b1e4b54-df76-4007-8ada-81e32db03ac9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9c884c5a-9695-4b0e-9bb6-0f805ca45a32
        userCondition: null
handle: block_text
hasTitleField: false
icon: ''
name: 'Block: Text'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
