color: null
fieldLayouts:
  5f68bb52-8a10-4ff0-82b2-13c9ad8ee07f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-13T10:29:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1268c5ea-5e4e-4fbf-8cb3-cea660e3148d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-13T10:29:37+00:00'
            elementCondition: null
            fieldUid: 31453c43-6490-4c7f-ae24-da061e930401 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9435c2a-b252-487e-bb6c-24f449ad734d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-13T10:29:37+00:00'
            elementCondition: null
            fieldUid: 7f970b21-4477-4584-8c42-bb2768e327c2 # Light Switch
            handle: lightSwitch
            includeInCards: false
            instructions: 'Switch image and text column order'
            label: Switched
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 808c26d7-57e5-4e59-8d3a-5ff5438a4ce4
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-13T10:29:37+00:00'
            elementCondition: null
            fieldUid: a536dc09-ff34-40c6-9e0f-ab3cc3f4ce8e # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff597d18-697d-4f40-93a2-5073a54dc05d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-13T11:13:57+00:00'
            elementCondition: null
            fieldUid: d71b8bcd-b412-49bf-95af-9df0c8410585 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1ea3783-39e5-48be-8a1b-ae1bf719f640
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3745d9fd-b891-4f93-860c-0373beecac0e
        userCondition: null
handle: block_imageAndText
hasTitleField: false
icon: ''
name: 'Block: Image and Text'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
