color: null
fieldLayouts:
  e38b7486-d270-4dcb-aa1b-f091fee8ddf8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-13T07:48:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2812d706-250f-4680-be06-6400f172499c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-13T07:48:42+00:00'
            elementCondition: null
            fieldUid: 31453c43-6490-4c7f-ae24-da061e930401 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7194915c-198c-4774-9ac4-ce16d895734e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ae5061a1-3342-49d5-8c7a-ff91decd7930
        userCondition: null
handle: block_image
hasTitleField: false
icon: ''
name: 'Block: Image'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
