allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  c8749448-ea75-405a-9ec6-7bf3eeddd3a5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-13T10:29:37+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 648c0fe1-b09f-4f06-ae84-374277216c64 # Link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a53b494e-6254-480a-bde4-4c05b4bf1f3f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2bebcd7c-7597-4963-9d90-cbeb3de31c77
        userCondition: null
    thumbFieldKey: null
handle: link
hasTitleField: false
icon: null
name: Link
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
