allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  b8e1916a-10d4-423b-ac46-e8c1f6f697a0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-23T08:36:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2066cfb8-1731-4aa2-8ff2-a6be8a3b17e6 # Plain Text Multiline
            handle: quote
            instructions: null
            label: Quote
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2cb47c4-0201-4846-9dce-acb9d70fe03a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-23T08:36:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 93116f68-b0f3-4e73-818b-9d4c0a2d4b57 # Headline
            handle: quoteAuthor
            instructions: null
            label: Author
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31ed5a2a-95f7-4b90-9043-dded3f111768
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-05-23T08:31:45+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 31453c43-6490-4c7f-ae24-da061e930401 # Image
            handle: backgroundImage
            instructions: null
            label: 'Background Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5914ea5-b4b6-4d53-9a45-ad6148dea470
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: ea1ef136-997d-46fb-8a7c-ff32c75d40c3
        userCondition: null
    thumbFieldKey: null
handle: quote
hasTitleField: false
icon: null
name: Quote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
