allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  eef6f4e8-aaab-43ad-a484-ac5fb10b854f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-13T07:48:42+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a536dc09-ff34-40c6-9e0f-ab3cc3f4ce8e # Text
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b1e4b54-df76-4007-8ada-81e32db03ac9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9c884c5a-9695-4b0e-9bb6-0f805ca45a32
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-23T11:45:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 890d662d-81cb-4901-b2cb-2e971c5beded # Alignment
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f509a48-d065-4fd3-8dc9-a638d421c61d
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 024766e8-8557-4c3a-a757-b8f2f44c6290
        userCondition: null
    thumbFieldKey: null
handle: text
hasTitleField: false
icon: null
name: Text
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
