headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
js: "return {\r\n  toolbar: [ 'bulletedList', 'numberedList' ],\r\n  code: {\r\n    indentSequence: '  ',\r\n  },\r\n  link: {\r\n    decorators: {\r\n      openInNewTab: {\r\n        attributes: {\r\n          target: '_blank',\r\n        },\r\n        label: 'Open in a new tab',\r\n        mode: 'manual',\r\n      }\r\n    }\r\n  },\r\n  removePlugins: ['ListProperties'],\r\n}"
name: Default
toolbar:
  - sourceEditing
  - heading
  - bold
  - bulletedList
  - numberedList
  - link
  - undo
  - redo
