defaultPlacement: end
fieldLayouts:
  1c158662-f0ce-49ea-8c8b-fc32915fc266:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 0f31d2cb-6600-461e-aabf-8620c3f2a4bd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: cef5c73a-dd2b-4702-bfc4-d542fbbe3887
            userCondition: null
            warning: null
          -
            attribute: newWindow
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: b1635840-dcf6-4086-95ca-163b082e859d
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: cfbdf45f-c0eb-49fb-b9d4-57291bf30f94
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 155debd4-b9ef-429b-b51a-5b5db740e34e
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 1f5ccbac-f2da-4409-b656-b762d6ac0de0
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: 2e4fe603-0dbf-457e-aac5-ec1ade465906
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 8307014b-95be-4850-a893-d136973d4348
        userCondition: null
handle: mainNavigation
instructions: ''
maxNodes: null
name: 'Main Navigation'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: all
siteSettings:
  d0b81f54-9f0b-47ff-8b70-ede217a82e9d: # $SITE_NAME
    enabled: true
sortOrder: 1
structure:
  maxLevels: null
  uid: eebbb745-8d3d-4ef4-942d-549ace8a1de0
