altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f69faf1a-4a8d-42c3-8d90-4a88169e5001:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0a636aef-4638-493f-96cf-aa7100f3d3e5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 72fc0e5d-7d00-4b05-9bb2-899d78a9e66f # Alt Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6317fa1-a3a9-4dad-9ff2-d3d90741833c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a6fb051-ad40-4976-811b-de8f4ae5d694 # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e583d8db-15d4-4c3e-af87-2cf5fa19a6af
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7ce712af-2024-42f5-876a-915e4107dbe2
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: images
transformSubpath: images
