altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  5acf4152-cc48-47d5-b4ec-56e129cd2994:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5586173b-b385-40f8-8625-3fa9c034b858
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 72fc0e5d-7d00-4b05-9bb2-899d78a9e66f # Alt Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 104e9875-1bd5-475f-b5ff-9151f19811f7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1a6fb051-ad40-4976-811b-de8f4ae5d694 # Caption
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15ce01f5-9d28-45d3-b505-cfd6928379a5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9e37b945-2f15-4a4e-953b-821123dc6829
        userCondition: null
    thumbFieldKey: null
fs: templateImages
handle: templateImages
name: 'Template Images'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: templateImages
transformSubpath: templateImages
