altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  2e3b2f10-8b9d-4ae4-8742-16d32cd2b2a2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 30c24bf9-5d6b-44ea-bb14-b22429e3f3df
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 72fc0e5d-7d00-4b05-9bb2-899d78a9e66f # Alt Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ecde24b-32a7-4d3f-964d-269fef883279
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a6fb051-ad40-4976-811b-de8f4ae5d694 # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa867a2a-6924-4f53-9d29-8b2739fce362
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f4d2d2ad-a8b4-434c-8c0e-4f3c572dfc98
        userCondition: null
fs: users
handle: users
name: Users
sortOrder: 4
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: users
transformSubpath: users
