columnSuffix: null
handle: eMail
instructions: null
name: E-Mail
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  types:
    - email
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
