columnSuffix: null
handle: linkVariant
instructions: null
name: 'Link Variant'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Primary
        -
          - value
          - primary
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Secondary
        -
          - value
          - secondary
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Link
        -
          - value
          - link
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
