columnSuffix: null
handle: linkBlock
instructions: null
name: Link
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 7c8c16e4-d5b0-4b0a-9d51-5c9f64a9a226 # Block: Link
  includeTableView: false
  maxEntries: 1
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
