columnSuffix: null
handle: linkBase
instructions: null
name: Link
searchable: false
settings:
  advancedFields:
    - target
    - download
  fullGraphqlData: false
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowedKinds
              - '*'
            -
              - showUnpermittedVolumes
              - ''
            -
              - showUnpermittedFiles
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'single:745244db-cd1b-4b14-ab0f-07d6ddcf070f' # Home
                - 'single:873f989e-0227-4995-a310-6b6fb4e377a3' # Kontakt
                - 'section:a94c302a-1da9-4e98-96b1-36d23ce0235b' # Seiten
            -
              - showUnpermittedSections
              - '1'
            -
              - showUnpermittedEntries
              - '1'
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - '1'
            -
              - allowCustomSchemes
              - ''
  types:
    - entry
    - email
    - tel
    - url
    - asset
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
