columnSuffix: null
handle: navigationsLinks
instructions: null
name: 'Navigations Links'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedEntries: false
  showUnpermittedSections: false
  sources:
    - 'single:745244db-cd1b-4b14-ab0f-07d6ddcf070f' # Home
    - 'single:873f989e-0227-4995-a310-6b6fb4e377a3' # Contact
    - 'section:a94c302a-1da9-4e98-96b1-36d23ce0235b' # Pages
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list-inline
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
